### ISSUE TITLE
分词对训练的影响

### ISSUE THREAD

**Issue by yangyaofei** [twairball/t2t_wmt_zhen#1]
请教一下,中文分词和不分词是不是对训练影响很大?我自己写的,不分词,char-base,跑出来很差,不知是真的分词的问题还是我自己的问题

**Comment by twairball** [comment]
大多数都用 jieba 做分词，但这个影响其实不大，因为他决定的是 vocab 大小
这方面的细节可以参考 Sennrich et al: https://arxiv.org/abs/1508.07909

**Comment by yangyaofei** [comment]
哦,谢谢
