### ISSUE TITLE
BLEU evaluation on Chinese

### ISSUE THREAD

**Issue by ChiZhangRIT** [twairball/t2t_wmt_zhen#4]
Thanks for sharing the code.

I was trying to run the code, but this is what I got:
```
./main/gen_orig.sh: line 6: t2t-datagen: command not found
```

BTW, how did you run BLEU evaluation on Chinese sentences? Did you use any tokenizer to get BLEU score?

**Comment by twairball** [comment]
hi, this code was based on a previous version of tensor2tensor -- it was merged into main repo so you can run the translation experiment there. 

Default tensor2tensor tokenizer was used, based on subword encoding (sennrich et al)
